#所有规则: https://dart-lang.github.io/linter/lints/index.html

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: true

linter:
  rules:
    - cancel_subscriptions