#所有规则: https://dart-lang.github.io/linter/lints/index.html

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: true

linter:
  rules:
    cancel_subscriptions: true
    constant_identifier_names: false
    prefer_const_constructors: false
    non_constant_identifier_names: false
    library_private_types_in_public_api: false
    depend_on_referenced_packages: false
    implementation_imports: false